### PR TITLE
Small additions

### PR DESCRIPTION
**Pull request by LuxLang**

### CODE REVIEW

**Comment by chrisjensen** [comment]
I see two additions: Place gambling, etc in the context of adversely addictive behaviours:
`adversely addictive behaviours (e.g. gambling, smoking tobacco, alcoholism, drug-addiction)`

and add `scams and any other illegal activities`

**Addictive Behaviours**
On the first, this limits the scope more than originally intended.
Adversely addictive behaviours is included separately as it refers to the new addictive behaviours being triggered by tech companies that [hack psychology](http://adage.com/article/digital/sean-parker-worries-facebook-rotting-children-s-brains/311238/).
By placing gambling, etc, within adversely addictive behaviours, it implies that those things are the full list of adversely addictive behaviours and implies that the above example is acceptable use.

**Illegal Activities**
Illegal activities is problematic as some states place legal restrictions on what many would consider to be legitimate forms of expression and organising (eg anti-union laws, anti-protest laws). This would make our software unusable to many groups that we support.

For this reason it's better to describe the specific activity objected too rather than to refer to illegal activities as a whole.

(scamming may be a legitimate one to add to the list, but I think we'd need to be more specific)

For these reasons, I don't think we should include these changes as they are.

**Comment by LuxLang** [comment]
> Adversely addictive behaviours is included separately as it refers to the new addictive behaviours being triggered by tech companies that hack psychology.

> By placing gambling, etc, within adversely addictive behaviours, it implies that those things are the full list of adversely addictive behaviours and implies that the above example is acceptable use.

I didn't intend to use that list as the full set of examples, but just as easy-to-understand examples that people can easily grasp.

"Including, but not limited to" would be a nice description of what I wanted.

To put things into perspective, the case you mentioned and that you wanted to address was something I imagined you might be going for, but it wasn't clear because it wasn't explicitly stated in the document. Because of that, I felt just saying _"adversely addictive behaviours"_ was a bit too open to interpretation, and I added the different cases to reduce the ambiguity a little bit.

But I'm all in favor of not contributing to addictive behaviors due to technology, so I wholeheartedly agree with you on that.

> Illegal activities is problematic as some states place legal restrictions on what many would consider to be legitimate forms of expression and organising (eg anti-union laws, anti-protest laws). This would make our software unusable to many groups that we support.

I was thinking of that scenario too, after I made the PR.
I agree that just mentioning "illegal activities" can be problematic.

> (scamming may be a legitimate one to add to the list, but I think we'd need to be more specific)

I'm not sure how to be more specific about it.
There are many different types of scams, but scamming in general is wrong, regardless of what form it takes.

Do you mean using a more technical/legal term for scam?
Would it be "fraudulent activity"?
"Confidence trick" is, I think, just as informal as "scam", so maybe "fraudulent activity" or "fraud" would be better.

**Comment by chrisjensen** [comment]
I'm not sure it's worthwhile trying to try to find a way to word these changes to make them work.

The kind of fraud described would not realistically be discouraged by this license and adding an exclusion for it may have unintended consequences: An extreme example would be [Jonothan Moylan](https://www.eurekastreet.com.au/article.aspx?aeid=41758), (an environmental activist who was charged with fraud), but lesser examples might include Greenpeace stunts at board meetings, or the Yes Men.

I'm mostly happy to accept the change for addictive behaviours, except that I'm not sure about alcoholism. Australia and other countries have very big drinking cultures, while I'm not a fan of this, I am concerned that if a restriction on alcoholism were included it would risk applying too broadly for meaningful adoption.

(This is why I felt #11 was necessary to describe the kind of balance we seek)

**Comment by LuxLang** [comment]
@chrisjensen Fair enough.

**Pull request closed without merging**
